/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author ioch
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario dell\\Desktop\\ProyectoCompiladores\\WhatsApp Image 2023-04-20 at 22.58.25.jpeg")); // NOI18N

        txtResultado1.setColumns(20);
        txtResultado1.setRows(5);
        jScrollPane2.setViewportView(txtResultado1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(326, 326, 326)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        
    JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);
        
        try {
            Reader leer = new BufferedReader(new FileReader(chooser.getSelectedFile()));
            Lexer lexer = new Lexer(leer);
            
            String resultadoDeTokes = "";
            String resultadoDePatrones = "";
            
            int operadoresAritmetico = 0;
            int operadoresAsignacion = 0;
            int identificadores = 0;
            int operacionesAgrupacion = 0;
            int palabrasReservadas = 0;
            int simbolosDePuntuacion = 0;
            int operadoresDeComparacion = 0;
            int cadena = 0;
            int numeros = 0;
            int decimales = 0;
            int logicos = 0;
            int booleanos = 0;
            int incrementales = 0;
            int errores = 0;
            int indefinido = 0;
            
            
            while (true) {                
            
                Tokens tokens = lexer.yylex();
                //si es la ultima linea del token, realiza la escritura final
                if (tokens == null){
                    resultadoDeTokes += "FIN";
                    txtResultado.setText(resultadoDeTokes);
                    txtResultado1.setText(resultadoDePatrones);
                    return;
                }
                
                switch (tokens) {
                    //se valida segun el tipo de token, para retornar una respuesta (aqui esta de forma muy general)
                    case ERROR:
                        resultadoDeTokes += "Error de token\n";
                        resultadoDePatrones += "(N , N-"+errores+")\n";
                        errores++;
                        break;
                    case INICIO:
                        break;
                    case opSuma: case opResta: case opMultiplicacion: case opDivision:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(A , A-"+operadoresAritmetico+")\n";
                        operadoresAritmetico++;
                        break;
                    case opIgual:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(B , B-"+operadoresAsignacion+")\n";
                        operadoresAsignacion++;
                        break;
                    case Identificador:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(C , C-"+identificadores+")\n";
                        identificadores++;
                        break;
                    case aParentesis: case cParentesis: case aLlave: case cLlave: case aCorchete: case cCorchete:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(D , D-"+operacionesAgrupacion+")\n";
                        operacionesAgrupacion++;
                        break;
                    case Reservadas:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(E , E-"+palabrasReservadas+")\n";
                        palabrasReservadas++;
                        break;
                    case finLine:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(F , F-"+simbolosDePuntuacion+")\n";
                        simbolosDePuntuacion++;
                        break;
                    case sigMayor: case sigMenor: case mayorIgual: case menorIgual: case comparacion: case diferente:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(G , G-"+operadoresDeComparacion+")\n";
                        operadoresDeComparacion++;
                        break;
                    case cadena:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(H , H-"+cadena+")\n";
                        cadena++;
                        break;
                    case Numero:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(I , I-"+numeros+")\n";
                        numeros++;
                        break;
                    case Decimal:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(J , J-"+decimales+")\n";
                        decimales++;
                        break;
                    case opOr: case opAnd:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(K , K-"+logicos+")\n";
                        logicos++;
                        break;
                    case booleano:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(L , L-"+booleanos+")\n";
                        booleanos++;
                        break;
                    case incremento: case decremento: case yoMas: case yoMenos:
                        resultadoDeTokes += lexer.lexeme + ": Es " + tokens + "\n";
                        resultadoDePatrones += "(M , M-"+incrementales+")\n";
                        incrementales++;
                        break;
                    default:
                        resultadoDeTokes +=  lexer.lexeme + " Token " + tokens + " no definido \n";
                        resultadoDePatrones += "(O , O-"+indefinido+")\n";
                        indefinido++;
                        break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtResultado1;
    // End of variables declaration//GEN-END:variables
}
